### PR TITLE
FIX: these methods would have name errors

### PR DESCRIPTION
**Pull request by tacaswell**

### CODE REVIEW

**Comment by ambarb** [comment]
@tacaswell these are pretty recent.  do we need to test or should we merge?

**Comment by tacaswell** [comment]
If I recall I found these via a static analysis linter and I think the code I changed can not be currently running properly so I suspect that means in is not actually used on the beamline.

It is probably safe to merge this PR, but then either tracking down how to make these code paths run on the beamline or just removing the classes (as they are not used!).

**Comment by ambarb** [comment]
The changes are some extra white space remove and code that only affects `class Lakeshore336Picky(Device)`. Should improve and definitely will not break anything that we cannot adapt to on the fly

 It looks like this class is found in two files so we should probably fix that (`startup/csx1/devices/devices.py` and `startup/csx1/devices/lakeshore.py`)

**Review by ambarb — COMMENTED** [review]
The changes are some extra white space remove and code that only affects class Lakeshore336Picky(Device). Should improve and definitely will not break anything that we cannot adapt to on the fly

It looks like this class is found in two files so we should probably fix that (startup/csx1/devices/devices.py and startup/csx1/devices/lakeshore.py)

**Review by ambarb — APPROVED** [review]

**Pull request merged**
